lint: upgrade to slim-v4
EGI-Federation/repository-template pull request #21
Opened 2021-05-26 07:10 UTC by gwarf

Slim version do not include rust, dotenv, armttk and pwsh: https://github.com/github/super-linter#slim-image

2021-05-26 10:03 UTC, enolfc requested changes

2021-05-26 10:03 UTC, enolfc commented on .github/workflows/lint.yml
> +        uses: github/super-linter@slim-v4
```suggestion
        uses: ghcr.io://github/super-linter@slim-v4
```

2021-05-26 10:16 UTC, gwarf commented on .github/workflows/lint.yml
> +        uses: github/super-linter@slim-v4
Oh! Good catch, thanks!

2021-05-26 10:18 UTC, gwarf commented
So it still fails :/

2021-05-26 10:21 UTC, gwarf commented
Saw this @enolfc : https://github.com/github/super-linter/issues/1596

2021-05-26 10:25 UTC, enolfc requested changes
Let's try like this

2021-05-26 10:25 UTC, enolfc commented on .github/workflows/lint.yml
> +        uses: ghcr.io://github/super-linter@slim-v4
```suggestion
        uses: ghcr.io/github/super-linter@slim-v4
```

2021-06-09 09:39 UTC, enolfc approved these changes
Finally works! Cool.

2021-06-09 09:39 UTC, merged